version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.5.0-browsers
      #- image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Build HTML
          command: echo "Build HTML step goes here"

workflows:
  
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
