version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.5.0-browsers
      #- image: circleci/node:14

    steps:

      - run:
          name: Set Git Credentials
          command: |
            git config user.email "alexis@neuronaagency.com"
            git config user.name "Alexis Aldana"
            git clone git@github-second:alz7xn/test.git

      #- checkout

      - run:
          name: Build HTML
          command: echo "Build HTML step goes here"

workflows:
  
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
